import prisma from '../lib/prisma.js';
import { serialize } from './serialize.js';

export class SeatUnavailableError extends Error {
  constructor({ passEventId, seatId }) {
    super(`Seat ${seatId} is not available for event ${passEventId}`);
    this.name = 'SeatUnavailableError';
    this.passEventId = passEventId;
    this.seatId = seatId;
  }
}

export class InsufficientPassCapacityError extends Error {
  constructor({ passTierId }) {
    super(`Insufficient capacity remaining on pass tier ${passTierId}`);
    this.name = 'InsufficientPassCapacityError';
    this.passTierId = passTierId;
  }
}

// --- PassEventSeat: per-event seat availability, RESERVED_SEAT tiers only ---

/**
 * One PassEventSeat row per (PassEvent, Seat) — created once, up front, the
 * moment a RESERVED_SEAT tier is attached to a PassEvent (called from the
 * admin route right after passEventRepository.createTier), the same way
 * ProductSize rows exist from product creation rather than being lazily
 * created on first order. This is what gives holdSeat/redeemSeat a
 * pre-existing row to run their atomic conditional UPDATE against.
 */
export async function initializeEventSeats({ passEventId, venueSectionId }, { client = prisma } = {}) {
  const seats = await client.seat.findMany({ where: { venueSectionId } });
  await client.passEventSeat.createMany({
    data: seats.map((seat) => ({ passEventId, seatId: seat.id })),
    skipDuplicates: true,
  });
}

export async function findEventSeats({ passEventId, venueSectionId }, { client = prisma } = {}) {
  const seats = await client.passEventSeat.findMany({
    where: { passEventId, seat: { venueSectionId } },
    include: { seat: true },
  });
  return serialize(seats);
}

/**
 * Places a short-lived hold on a seat before checkout even starts (the
 * fan clicking a seat on the map) — the one genuinely pre-checkout-order
 * reservation step this category needs, since seat selection has to happen
 * before the buyer fills out checkout details. Atomic conditional UPDATE,
 * same shape as productRepository.decrementStock: `available`, or `held`
 * but past its own expiry, are both fair game; anything else (held by
 * someone else and still live, or sold) means 0 rows match and this
 * throws. holdToken is generated by the caller (route) and returned to the
 * browser — required again to release or to redeem, so a lapsed holder can
 * never touch a seat someone else has since gone on to hold.
 */
export async function holdSeat({ passEventId, seatId, holdToken, holdMinutes = 10 }, { client = prisma } = {}) {
  const heldUntil = new Date(Date.now() + holdMinutes * 60 * 1000);
  const result = await client.passEventSeat.updateMany({
    where: {
      passEventId,
      seatId,
      OR: [{ status: 'available' }, { status: 'held', heldUntil: { lt: new Date() } }],
    },
    data: { status: 'held', heldUntil, holdToken },
  });
  if (result.count === 0) throw new SeatUnavailableError({ passEventId, seatId });
  return findEventSeat({ passEventId, seatId }, { client });
}

export async function findEventSeat({ passEventId, seatId }, { client = prisma } = {}) {
  const eventSeat = await client.passEventSeat.findUnique({
    where: { passEventId_seatId: { passEventId, seatId } },
    include: { seat: true },
  });
  return serialize(eventSeat);
}

/**
 * Explicit release (a fan deselecting a seat before checkout). Gated on
 * holdToken matching — releasing a hold you don't own, or one that's
 * already lapsed and been reassigned to someone else, is a silent no-op,
 * never an error and never a deletion of someone else's live hold. A
 * lapsed-and-unreassigned hold is also cleaned up passively the next time
 * anyone calls holdSeat on it; this function isn't the only path back to
 * `available`.
 */
export async function releaseSeat({ passEventId, seatId, holdToken }, { client = prisma } = {}) {
  await client.passEventSeat.updateMany({
    where: { passEventId, seatId, holdToken, status: 'held' },
    data: { status: 'available', heldUntil: null, holdToken: null },
  });
}

/**
 * Converts a held seat to sold — must run inside the order-creation
 * transaction (same "no default client" enforcement as decrementStock).
 * Re-checks holdToken so an order can never redeem a seat it didn't
 * actually (still) hold, closing the same TOCTOU gap re-validated for
 * promo codes and gateway fees elsewhere in checkout.
 */
export async function redeemSeat({ passEventId, seatId, holdToken }, { client } = {}) {
  if (!client) throw new Error('redeemSeat must be called with a transaction client');
  const result = await client.passEventSeat.updateMany({
    where: { passEventId, seatId, holdToken, status: 'held' },
    data: { status: 'sold' },
  });
  if (result.count === 0) throw new SeatUnavailableError({ passEventId, seatId });
}

/**
 * Symmetric inverse of redeemSeat — used when a Pass-carrying order's
 * payment fails/expires. Keyed by the PassEventSeat's own id (what
 * Pass.passEventSeatId already points at), not the (passEventId, seatId)
 * compound holdSeat/redeemSeat use — the caller already has this id off
 * the Pass row, no extra lookup needed.
 */
export async function releaseSoldSeat(passEventSeatId, { client } = {}) {
  if (!client) throw new Error('releaseSoldSeat must be called with a transaction client');
  await client.passEventSeat.updateMany({
    where: { id: passEventSeatId, status: 'sold' },
    data: { status: 'available', heldUntil: null, holdToken: null },
  });
}

// --- PassTier capacity (GENERAL_ADMISSION tiers only) ---

/**
 * Mirrors productRepository.decrementStock's conditional-update-not-
 * read-then-write shape. `sold + quantity <= capacity` isn't directly
 * expressible as a Prisma filter (comparing two columns plus a literal),
 * so it's rearranged to `sold <= capacity - quantity` — capacity is read
 * first (a rarely-changing, admin-set value) and used as a literal in the
 * WHERE, the same technique promoCodeRepository.tryRedeem already used for
 * `redemptionCount < maxRedemptions`.
 */
export async function decrementTierCapacity({ passTierId, quantity }, { client } = {}) {
  if (!client) throw new Error('decrementTierCapacity must be called with a transaction client');
  const tier = await client.passTier.findUnique({ where: { id: passTierId } });
  if (!tier || tier.capacity == null) {
    throw new Error(`Pass tier ${passTierId} has no GENERAL_ADMISSION capacity configured`);
  }
  const result = await client.passTier.updateMany({
    where: { id: passTierId, sold: { lte: tier.capacity - quantity } },
    data: { sold: { increment: quantity } },
  });
  if (result.count === 0) throw new InsufficientPassCapacityError({ passTierId });
}

/** Symmetric inverse of decrementTierCapacity. */
export async function restoreTierCapacity({ passTierId, quantity }, { client } = {}) {
  if (!client) throw new Error('restoreTierCapacity must be called with a transaction client');
  await client.passTier.updateMany({
    where: { id: passTierId, sold: { gte: quantity } },
    data: { sold: { decrement: quantity } },
  });
}

// --- Pass: the individual scannable admission credential ---

const DEFAULT_INCLUDE = {
  passEvent: { include: { venue: true, organization: { select: { id: true, name: true, slug: true } } } },
  passTier: true,
  passEventSeat: { include: { seat: true } },
};

export async function findById(id, { include = DEFAULT_INCLUDE, client = prisma } = {}) {
  const pass = await client.pass.findUnique({ where: { id }, include });
  return serialize(pass);
}

export async function findByQrToken(qrToken, { include = DEFAULT_INCLUDE, client = prisma } = {}) {
  const pass = await client.pass.findUnique({ where: { qrToken }, include });
  return serialize(pass);
}

export async function findByOrderId(orderId, { include = DEFAULT_INCLUDE, client = prisma } = {}) {
  const passes = await client.pass.findMany({ where: { orderId }, include });
  return serialize(passes);
}

export async function findByUserId(userId, { include = DEFAULT_INCLUDE, client = prisma } = {}) {
  const passes = await client.pass.findMany({
    where: { order: { userId } },
    include,
    orderBy: { createdAt: 'desc' },
  });
  return serialize(passes);
}

/**
 * Creates the Pass row and its opening PassLog entry — must run inside the
 * order-creation transaction, alongside redeemSeat/decrementTierCapacity.
 * Issued directly (no separate "reserved" pre-status): a Pass only comes
 * into existence once an Order successfully commits, at which point the
 * seat/capacity reservation has already succeeded — same "reserved at
 * placement, not payment confirmation" rule Merchandise stock already
 * follows.
 */
export async function issuePass({ orderId, passEventId, passTierId, passEventSeatId, price }, { client } = {}) {
  if (!client) throw new Error('issuePass must be called with a transaction client');
  const pass = await client.pass.create({
    data: { orderId, passEventId, passTierId, passEventSeatId, price, status: 'issued' },
  });
  await client.passLog.create({
    data: { passId: pass.id, type: 'created', actor: 'system', message: 'Pass issued at order placement' },
  });
  return serialize(pass);
}

export const PASS_TRANSITIONS = {
  issued: ['checked_in', 'cancelled', 'refunded'],
  checked_in: [],
  cancelled: [],
  refunded: [],
};

export class InvalidPassTransitionError extends Error {
  constructor(fromStatus, toStatus) {
    super(`Cannot transition Pass from "${fromStatus}" to "${toStatus}"`);
    this.name = 'InvalidPassTransitionError';
    this.fromStatus = fromStatus;
    this.toStatus = toStatus;
  }
}

/**
 * The one real transition primitive for Pass.status — exact mirror of
 * shipmentRepository.transition: atomic CAS on the observed current
 * status (a second concurrent transition finds zero matching rows and
 * no-ops rather than racing), validated against PASS_TRANSITIONS first,
 * one typed PassLog row per applied transition. A check-in scan is
 * literally `transition(passId, 'checked_in', { actor: 'admin', actorUserId, metadata: { gate } })`.
 */
export async function transition(passId, toStatus, { actor = 'admin', actorUserId, message, metadata, client = prisma } = {}) {
  const current = await client.pass.findUnique({ where: { id: passId } });
  if (!current) return { applied: false, reason: 'not_found' };

  const allowed = PASS_TRANSITIONS[current.status] || [];
  if (!allowed.includes(toStatus)) {
    throw new InvalidPassTransitionError(current.status, toStatus);
  }

  const timestampField = toStatus === 'checked_in' ? { checkedInAt: new Date() } : {};

  const result = await client.pass.updateMany({
    where: { id: passId, status: current.status },
    data: { status: toStatus, ...timestampField },
  });
  if (result.count === 0) return { applied: false, reason: 'race_lost' };

  await client.passLog.create({
    data: {
      passId,
      type: 'status_changed',
      actor,
      actorUserId,
      fromStatus: current.status,
      toStatus,
      message: message || `Pass ${current.status} → ${toStatus}`,
      metadata,
    },
  });

  return { applied: true, fromStatus: current.status, toStatus };
}

export default {
  initializeEventSeats,
  findEventSeats,
  findEventSeat,
  holdSeat,
  releaseSeat,
  redeemSeat,
  releaseSoldSeat,
  decrementTierCapacity,
  restoreTierCapacity,
  findById,
  findByQrToken,
  findByOrderId,
  findByUserId,
  issuePass,
  transition,
  PASS_TRANSITIONS,
  SeatUnavailableError,
  InsufficientPassCapacityError,
  InvalidPassTransitionError,
};
